# First Finger (Index finger)
sh_ffj0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: FFJ2
  max_force: 10
  friction_deadband: 0
sh_ffj3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: FFJ3
  max_force: 10
  friction_deadband: 0
sh_ffj4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: FFJ4
  max_force: 10
  friction_deadband: 0


# Middle Finger
sh_mfj0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: MFJ2
  max_force: 10
  friction_deadband: 0
sh_mfj3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: MFJ3
  max_force: 10
  friction_deadband: 0
sh_mfj4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: MFJ4
  max_force: 10
  friction_deadband: 0


# Ring Finger
sh_rfj0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: RFJ2
  max_force: 10
  friction_deadband: 0
sh_rfj3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: RFJ3
  max_force: 10
  friction_deadband: 0
sh_rfj4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: RFJ4
  max_force: 10
  friction_deadband: 0


# Little Finger
sh_lfj0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: LFJ2
  max_force: 10
  friction_deadband: 0
sh_lfj3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: LFJ3
  max_force: 10
  friction_deadband: 0
sh_lfj4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: LFJ4
  max_force: 10
  friction_deadband: 0
sh_lfj5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: LFJ5
  max_force: 10
  friction_deadband: 0


# Thumb
sh_thj1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: THJ1
  max_force: 10
  friction_deadband: 0
sh_thj2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: THJ2
  max_force: 10
  friction_deadband: 0
sh_thj3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: THJ3
  max_force: 10
  friction_deadband: 0
sh_thj4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: THJ4
  max_force: 10
  friction_deadband: 0
sh_thj5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: THJ5
  max_force: 10
  friction_deadband: 0


# Wrist
sh_wrj1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: WRJ1
  max_force: 10
  friction_deadband: 0
sh_wrj2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: WRJ2
  max_force: 10
  friction_deadband: 0


