la_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  topic: "la_trajectory_controller"
  joints:
     - la_shoulder_pan_joint
     - la_shoulder_lift_joint
     - la_elbow_joint
     - la_wrist_1_joint
     - la_wrist_2_joint
     - la_wrist_3_joint
  gains:
    la_shoulder_pan_joint: {p: 600.0, i: 500.0, d: 100.0, i_clamp: 100.0}
    la_shoulder_lift_joint: {p: 1500.0, i: 500.0, d: 100.0, i_clamp: 100.0}
    la_elbow_joint: {p: 1500.0, i: 500.0, d: 100.0, i_clamp: 100.0}
    la_wrist_1_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    la_wrist_2_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    la_wrist_3_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5

      la_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      la_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      la_elbow_joint: {trajectory: 0.1, goal: 0.1}
      la_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      la_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      la_wrist_3_joint: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
